### ISSUE TITLE
Code coloring and Firefox Dark Mode Conflicts

### ISSUE THREAD

**Issue by DailyAlice** [tinkerbell/tinkerbell.org#113]
## Expected Behaviour
Code coloring in the docs and on the website should look something like:
<img width="898" alt="Screen Shot 2020-07-28 at 1 08 57 PM" src="https://user-images.githubusercontent.com/7660123/88704849-4fe0d400-d0d4-11ea-983c-a9f6d9161c1d.png">

## Current Behaviour
But (in at least Firefox) with the "user prefers dark mode" option set it looks like:
![image](https://user-images.githubusercontent.com/7660123/88705033-959d9c80-d0d4-11ea-90fe-e705eb2377c1.png)

## Possible Solution
Might need to take a look at a few other browsers/dark mode options, as well as how our Hugo does colors

**Comment by gianarb** [comment]
I can't replicate anymore not sure

```
FireFox 79.0 (64-bit)
```

![Screenshot 2020-08-18 at 20 53 39](https://user-images.githubusercontent.com/1630267/90553617-fa5c8c00-e194-11ea-9c8e-1258a4ac77de.png)

**Comment by DailyAlice** [comment]
with the switch over to mkdocs and moving the source of the docs to tinkerbell/tinkerbell-docs, I'm not sure this issue is relevant any more. Gonna close, and if something similar re-occurs, we can track in a new issue.
