### ISSUE TITLE
Update logo at footer

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell.org#152]
hi @geriadam please change to Equinix Metal
Thanks.

**Comment by felixwidjaja** [comment]
hi @geriadam can you also update https://tinkerbell.org/ using all white logo?
![image](https://user-images.githubusercontent.com/4198376/95221628-d6770780-0821-11eb-8179-c10debd1eb3e.png)

**Comment by felixwidjaja** [comment]
Looks good @geriadam 
Can we proceed?

**Comment by thomcrowe** [comment]
Can we please get this updated asap?

**Comment by felixwidjaja** [comment]
@thomcrowe all is done since yesterdays sir.
https://docs.tinkerbell.org/
https://tinkerbell.org/

**Comment by thomcrowe** [comment]
Hard refresh and it's there. Y'all are awesome.

**Comment by felixwidjaja** [comment]
🤘
