### ISSUE TITLE
Template command example incomplete

### ISSUE THREAD

**Issue by charlottemach** [tinkerbell/tinkerbell.org#158]
Tiny issue with incomplete command in the example on https://tinkerbell.org/docs/cli/template/ 

## Current docs

**Examples**

```
template create --name hello-world < ./hello-world.yml
>
Created Template:  b8dbcf07-39dd-4018-903e-1748ecbd1986
```
in https://github.com/tinkerbell/tinkerbell.org/blob/master/content/docs/cli/template.md.
## Should be

**Examples**

```
tink template create --name hello-world < ./hello-world.yml
>
Created Template:  b8dbcf07-39dd-4018-903e-1748ecbd1986
```

**Comment by DailyAlice** [comment]
@charlottemach I opened a PR over in the tinkerbell-docs repo which should fix this. https://github.com/tinkerbell/tinkerbell-docs/pull/27, if you want to make sure that I got the right thing.

The source of the docs moved a little bit back; sorry for the confusion that may have caused.

**Comment by charlottemach** [comment]
looks good, thank you @DailyAlice !
