### ISSUE TITLE
Tinkerbell.org/docs is still accessible

### ISSUE THREAD

**Issue by thomcrowe** [tinkerbell/tinkerbell.org#160]
## Expected Behaviour

We moved our docs to docs.tinkerbell.org and the tinkerbell.org/docs need to be removed.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by ronggur** [comment]
@geriadam let's add redirections from/docs to docs.tinkerbell.org and completely remove docs from tinkerbell.org

**Comment by felixwidjaja** [comment]
@ronggur @geriadam can you "kill" https://tinkerbell.org/docs/ 
(either redirect or really kill)
thank you.

**Comment by jacobsmith928** [comment]
please really kill and create any redirects to the new https://docs.tinkerbell.org/

**Comment by ronggur** [comment]
all content has been removed and redirections also in place
