### ISSUE TITLE
Local setup docs fix

### ISSUE THREAD

**Issue by markyjackson-taulia** [tinkerbell/tinkerbell.org#168]
Currently the local setup section of the docs references `cd /vagrant && source .env && cd deploy` which according to the [setup.sh](https://github.com/tinkerbell/tink/blob/master/setup.sh#L483) should be `cd /vagrant && source .envrc && cd deploy`

**Comment by tstromberg** [comment]
This was resolved by https://github.com/tinkerbell/tink/pull/483
