### ISSUE TITLE
Sitemap Update: Docs

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell.org#175]
Hi @ronggur 

In https://tinkerbell.org/sitemap.xml :

1. Add `docs.tinkerbell.org`.
2. Remove https://tinkerbell.org/sitemap-docs.xml
3. Remove anything relates with https://tinkerbell.org/docs/

Thanks.

**Comment by ronggur** [comment]
@felixwidjaja since /docs related to content, should we ask about it to @thomcrowe or @rainleander first?

also apparently @geriadam already create a pull request for redirection https://github.com/tinkerbell/tinkerbell.org/pull/162

**Comment by thomcrowe** [comment]
Please go ahead and remove everything in Tinkerbell.org/docs

**Comment by ronggur** [comment]
@thomcrowe thanks

**Comment by rainleander** [comment]
And I helped! ;-)

**Comment by ronggur** [comment]
@felixwidjaja, @geriadam already update the sitemap

**Comment by felixwidjaja** [comment]
Hi @ronggur looks like sitemap problem detected, as explained in Slack; please update sir. Thanks.

**Comment by ronggur** [comment]
@felixwidjaja I'll close this issue and open another one
