### ISSUE TITLE
Footer update with CNCF

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell.org#193]
hi @geriadam 

Back story:
We are working with the Cloud Native Computing Foundation to get Tinkerbell donated to their organisation. One of the point we have to address is to get the website inline with their style guide https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices

Please update both homepage's and doc's footers. Just like this:
![image](https://user-images.githubusercontent.com/4198376/105379378-58f3cd80-5c3f-11eb-9096-4053b22a077e.png)
![image](https://user-images.githubusercontent.com/4198376/105379391-5c875480-5c3f-11eb-8bcf-439e8f203f4a.png)

Thanks.

Requested by @gianarb

**Comment by gianarb** [comment]
Thanks!

**Comment by felixwidjaja** [comment]
Hi @geriadam looks like we haven't follow the rule firmly. The text & link should be like this: https://goharbor.io/

Below is the mockup. Thanks.
![image](https://user-images.githubusercontent.com/4198376/107000458-79cd2e80-67ba-11eb-9949-4ae91f2e5a35.png)

**Comment by gianarb** [comment]
Hello @felixwidjaja @geriadam , any news about this bit of work?

Thanks

**Comment by felixwidjaja** [comment]
Sorry @gianarb I forgot completely to remind @geriadam about this.

**Comment by gianarb** [comment]
I think this is done! Thanks a lot!

**Comment by felixwidjaja** [comment]
Sweet!
