### ISSUE TITLE
hello-world example should direct users on how to fulfill prerequisites

### ISSUE THREAD

**Issue by tstromberg** [tinkerbell/tinkerbell.org#200]
If you stumble into https://docs.tinkerbell.org/workflows/hello-world-workflow/ the wrong way, you will get very confused as it assumes knowledge of the provisioner & worker, and that it is already setup. We provide no guidance to users who do not meet the prerequisites. 

As there is already a lot of new terminology for users sort out, we can reduce the cognitive overhead of learning Tinkerbell through copious use of hyperlinks. 

My thoughts lean something toward:

```
## A Hello-World Workflow

The "Hello World" example uses an example <a href="?">hardware data</a>, <a href="?"> template</a>, and <a href="?">workflow</a> to show off some basic Tinkerbell functionality, and the interaction between a <a href="?">Provisioner</a> and a <a href="?">Worker</a>. It uses the hello-world docker image as an example task that could be performed on a Worker as part of a workflow.
```

## Prerequisites

This tutorial assumes that you already Tinkerbell up and running. If you do not yet, please check-out our <a href="?>Getting Started</a> guide.

This tutorial also assumes that you have a <a href="?">Worker</a>  that has not yet been brought up, or can be restarted.
```

**Comment by jacobweinstock** [comment]
this example section has been removed.
