### ISSUE TITLE
Move Tinkerbell slack from company to CNCF Slack

### ISSUE THREAD

**Issue by caniszczyk** [tinkerbell/tinkerbell.org#204]
https://tinkerbell.org/community/contact/

It's currently on a company Slack which needs to change and move to the neutral slack.cncf.io

Work with @amye to make this happen

**Comment by markyjackson-taulia** [comment]
I have started dialog with the CNCF to start this process

**Comment by markyjackson-taulia** [comment]
Awaiting response from Amy with the CNCF. SLack DM sent in CNCF slack.

**Comment by amye** [comment]
Checking on availability for team here, standby.

**Comment by amye** [comment]
@idvoretskyi will be working with you all on this one!

**Comment by markyjackson-taulia** [comment]
Thank you @amye 
@idvoretskyi  I will ping you in my AM (due to tz difference)

**Comment by markyjackson-taulia** [comment]
This action has been completed and a CNCF slack DM sent to @idvoretskyi  with a link to the download
