### ISSUE TITLE
tinkerbell.org web site down (Netlify issues)

### ISSUE THREAD

**Issue by vielmetti** [tinkerbell/tinkerbell.org#219]
## Expected Behaviour

https://tinkerbell.org should show the main web page for the project.

## Current Behaviour

Instead, it's showing a Netlify error.

## Possible Solution

The current diagnosis is that this is a billing related issue.

## Context

Noticed by several teams.

**Comment by chrisdoherty4** [comment]
Hi. Thanks for raising the alarm. The site seems to be working right now, can you validate all is good your end?

**Comment by displague** [comment]
A temporary billing account has been added and the Netlify team and site is bing transferred a the CNCF account.

Thanks @mmlb @vielmetti @RobertKielty!

**Comment by vielmetti** [comment]
Site is back up as noted, marking this as complete. (The behind the scenes billing arrangements are also now under control, thanks all.)
