### ISSUE TITLE
Add an FAQ to the website

### ISSUE THREAD

**Issue by mrmrcoleman** [tinkerbell/tinkerbell.org#23]
When potential users are evaluating Tinkerbell they will naturally want to know how it is better or different than current solutions in the market. This is evidenced by the recent commentary on Reddit: 
https://www.reddit.com/r/selfhosted/comments/gdyy9p/open_sourcing_tinkerbell_for_automated_baremetal/

We can build up the FAQ as we go but a good base line of questions from the link above are:

- How does Tinkerbell compare to DigitalRebar?
- How does Tinkerbell compare to Foreman discovery?
- How does Tinkerbell compare to Canonical MAAS?

**Proposed first list of questions:**

1.  Does Tinkerbell work outside of Packet's hosting service, and has this been tested?
 
Yes, it will work outside of Packet. Our default setup script should work on any install of Ubuntu and CentOS.
 
2.  Does using Tinkerbell rely on having a Packet account?

No
 
3.  Can Tinkerbell be used to install OSes without Internet access (where both the Provider and Worker hosts are in an isolated network)?

Yes
 
4.  What operating systems is Tinkerbell able to install?

Any! Out of the box, we are endeavoring to provide installation workflows for deb and rpm-based systems, but it can be used for anything (as it includes a generic workflow engine).
 
5.  Can Tinkerbell install operating systems using their original, unmodified ISO images?

Yes
 
6.  Which server makes and models is Tinkerbell able to install operating systems on?

Currently works on any system with IPMI, with special support for Dells (racadm). Host-side, our installation has support for a lot of NICs, e.g. Broadcom, Intel, Netronome, Mellanox, and a few others out of the box.
 
7.  Does Tinkerbell have code to support (installing OSes on) specific server makes/models, or does it use standard interfaces only?

Our out of the box experience should allow you to install Ubuntu and CentOS easily.
 
8.  Is Tinkerbell able to operate remote server power settings (power on; power off)?  How about resetting?

Yes, via the pbnj microservice (https://github.com/tinkerbell/pbnj)
 
9.  When using Tinkerbell to install an operating system, are there any operations that need manual intervention?

Nothing that we have created needs manual intervention
 
10. Does Tinkerbell use each operating system's native network installer program, or does it install using a different method?

It depends on the operating system, the installation environment supports non-NM and NM for rpm-based systems, and the standard deb-based network interfaces.

**Comment by mrmrcoleman** [comment]
@felixwidjaja Can you start working on this FAQ page please?

**Comment by felixwidjaja** [comment]
@ronggur when time, please...

[Tinkerbell-FAQ-1.psd.zip](https://github.com/tinkerbell/tinkerbell.org/files/4733958/Tinkerbell-FAQ-1.psd.zip)
