### ISSUE TITLE
Wording in "How Does it Work?"

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell.org#30]
Need revision about the major components quantity @mrmrcoleman 
https://deploy-preview-27--festive-goldwasser-489842.netlify.app/

**Comment by ronggur** [comment]
hi @mrmrcoleman if you already have the new wording, let me know I can change it

**Comment by mrmrcoleman** [comment]
Morning. It wasn't my intention that you would wait for me on this as it's a minor thing.

Here's my suggestion for updated text:

"Tinkerbell has three major components: a DHCP server (oots), a workflow engine (tink), an in-memory operating system (osie) and a metadata service (hegel). The workflow engine is comprised of a server and a CLI, which communicate over gRPC. The CLI is used to create a workflow along with its building blocks, templates and targets."

**Comment by felixwidjaja** [comment]
Hi @mrmrcoleman 

Did you mean **four** major components? @ronggur took the liberty to put _four_ instead of _three_. Let us know if you want _three_.

Thanks.

**Comment by mrmrcoleman** [comment]
I did mean four, thanks @ronggur !

**Comment by felixwidjaja** [comment]
@mmlb, other than `oots` -> `Boots`, do you have any other concern? Thanks.

**Comment by mmlb** [comment]
nope, lgtm.

**Comment by felixwidjaja** [comment]
Thanks @mmlb.
@ronggur all yours sir.

**Comment by felixwidjaja** [comment]
and it just handled by @gauravgahlot . closing now.
