### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell.org#37]
@jacobsmith928 will help.

![image](https://user-images.githubusercontent.com/4198376/81705287-14514900-9499-11ea-93c9-a6645d22e723.png)

**Comment by jacobsmith928** [comment]
<title>Tinkerbell - Bare Metal Automation</title>
<meta name=description content="A flexible, open source bare metal provisioning and workflow engine.">


<meta property="og:title" content="Tinkerbell, a flexible open-source bare metal provisioning engine.">

**Comment by ronggur** [comment]
it seems need additional og:description https://deploy-preview-40--festive-goldwasser-489842.netlify.app

**Comment by ronggur** [comment]
og:description has been added

**Comment by felixwidjaja** [comment]
@ronggur , from @jacobsmith928 
Instead of “Tinkerbell for Bare Metal” how about “Flexible automation for bare metal”
This is because we have the domain right above it.

**Comment by felixwidjaja** [comment]
@ronggur new update coming up:

Title: Tinkerbell - Bare Metal Automation
Description: Tinkerbell is an open-source bare metal provisioning engine, built for a cloud native world and maintained by the team at Packet.

**Comment by mrmrcoleman** [comment]
@ronggur is this related to this PR?

https://github.com/tinkerbell/tinkerbell.org/pull/40

**Comment by ronggur** [comment]
@mrmrcoleman yes correct
