### ISSUE TITLE
Slack: More Guided

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell.org#39]
**Community Slack**
> Tinkerbell leverages Packet's community Slack channel. Please join and look for the #tinkerbell channel to get involved!
[[Join Packet Community on Slack]](https://slack.packet.net/)

Mockup:
![image](https://user-images.githubusercontent.com/4198376/81777626-76529280-951b-11ea-9b63-5bc23e488b4d.png)

Could we utilize this secondary nav to have a page with URL?
![image](https://user-images.githubusercontent.com/4198376/81776232-ae0c0b00-9518-11ea-9509-9272af6ec8d4.png)

And, after this page has URL, we shall point the Landing's main nav "**Slack Channel**" to it also (instead of to https://slack.packet.net/)

**Comment by mrmrcoleman** [comment]
This is great @felixwidjaja !

**Comment by ronggur** [comment]
deploy preview https://deploy-preview-42--festive-goldwasser-489842.netlify.app/community-slack/

**Comment by felixwidjaja** [comment]
Thanks @ronggur can you make the _secondary nav_ has **active style**? Simple **underline** just like in mockup.

**Comment by ronggur** [comment]
@felixwidjaja updated https://deploy-preview-42--festive-goldwasser-489842.netlify.app/community-slack/

**Comment by felixwidjaja** [comment]
Sold!
