### ISSUE TITLE
Logo SVG

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell.org#43]
Thanks @ronggur 
[Tinkerbell_Lockup_white_horz.svg.zip](https://github.com/tinkerbell/tinkerbell.org/files/4623626/Tinkerbell_Lockup_white_horz.svg.zip)

**Comment by ronggur** [comment]
@felixwidjaja ready https://deploy-preview-47--festive-goldwasser-489842.netlify.app/

**Comment by felixwidjaja** [comment]
Sweet.
