### ISSUE TITLE
Add Google Analytics to tinkerbell.org

### ISSUE THREAD

**Issue by mrmrcoleman** [tinkerbell/tinkerbell.org#51]
We would like to know how much traffic we're getting and which pages are popular. Please add GA to tinkerbell.org and ping me for the tracking code.

**Comment by felixwidjaja** [comment]
Hi @mrmrcoleman 
@ronggur can help paste the tracking code.

**Comment by mrmrcoleman** [comment]
Thanks @felixwidjaja

**Comment by felixwidjaja** [comment]
Hi @ronggur here's the Google Anayltics code

`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-52258647-10"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-52258647-10');
</script>`

**Comment by ronggur** [comment]
already made new PR https://github.com/tinkerbell/tinkerbell.org/pull/62
