### ISSUE TITLE
More obvious <a> in docs

### ISSUE THREAD

**Issue by felixwidjaja** [tinkerbell/tinkerbell.org#52]
https://tinkerbell.org/examples/hello-world/
![image](https://user-images.githubusercontent.com/4198376/82202061-8a3b3180-992b-11ea-8b82-5d8ad39f7d35.png)
1. @ronggur can you edit theme for `<a>` to be the underlined? Hover will change the color, or lose the underline. 
2. While you at it, please edit the link to https://tinkerbell.org/setup/ because the current one is 404.

*Thanks to Alex Ellis for this.

**Comment by ronggur** [comment]
new PR ready https://github.com/tinkerbell/tinkerbell.org/pull/61

**Comment by felixwidjaja** [comment]
I think the code was replaced, accidently. Could you please reapply @ronggur ?
