### ISSUE TITLE
Add requirements section to documentation

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tinkerbell.org#55]
It would be great to have following requirements of Tinkerbell included in the documentation, perhaps new section called "Requirements".

- OS for server:
  - As far as I know, currently Ubuntu 16.04/20.04 and some CentOS versions are supported by `setup.sh` script
- CPU, RAM, disk:
  - I test on 2 vCPUs and 4 GB of RAM and that seems to be sufficient
  - 20 GB disk seems to be sufficient (including OS)
- CPU architecture of workers and Tinkerbell server:
  - e.g. does it work on ARM?
- Network:
  - As far as I know, L2 network is required with ability to run your own DHCP server
- Workers:
  - workers must be able to boot from network using iPXE

**Comment by DailyAlice** [comment]
Thinking about this a little bit. Right now we have descriptions of Provisioners and Workers on the Architecture page: https://tinkerbell.org/architecture/

Those sections could be expanded to include the requirements listed here. I think that might be my initial approach.
