### ISSUE TITLE
Lightweight Portal

### ISSUE THREAD

**Issue by mrmrcoleman** [tinkerbell/tinkerbell.org#58]
From notes from Nathan:

Build a lightweight portal that would say “here’s your hardware that’s in this facility, here are your templates, your workflows.” Also allow users to create new templates and workflows.

Not a recreation of the multi tenant staff portal.

Extra notes:

1. Switch UI so Hardware shows a list and then you can edit, delete and upload within that page.
2. System status: List running containers
3. About page include running versions
4. Doesn't need to be branded like Tinkerbell, think more like Google Console.
5. Assuming PBNJ is running rebooting or kicking off a workflow through the UI
6. Inspect container registry to see which containers are available.

**Comment by gauravgahlot** [comment]
@mrmrcoleman That's ironic. 😃 
I thought about this when we started with Tinkerbell and started with a personal project (definitely OSS) called _Frawn_. I recently renamed it to _Tink-Wizard_ and made the new repo public. 
You can access the project deployed with some dummy data here: https://go.aws/2XcNhxE
This is a work in progress under the repo: https://github.com/gauravgahlot/tink-wizard

I'm excited to know your thoughts on this.

**Comment by mrmrcoleman** [comment]
@gauravgahlot This looks great! Nice work.
@nathangoulding Thoughts?

**Comment by DailyAlice** [comment]
It seems we now have a repository for work on a UI/portal - https://github.com/tinkerbell/portal

I'm going to assume that issues and work related to it will be tracked over there. Closing!
