### ISSUE TITLE
Add a Tinkerbell Collaborator page to the website

### ISSUE THREAD

**Issue by thomcrowe** [tinkerbell/tinkerbell.org#79]
We need a contributors' page for Tinkerbell.org

We need the contributors' name, GitHub handle, Twitter handle, and avatars.

https://docs.google.com/spreadsheets/d/1pLlyh5A3ZIhp8ePAxWY8CTvhUSm5rBXlGQ7pneoG50I/edit?usp=sharing

@felixwidjaja has created this mockup
![Tinkerbell-Contributor Mockup](https://user-images.githubusercontent.com/7960458/84919247-4dc43800-b087-11ea-9b18-604fd9f45327.jpg)

**Comment by jacobsmith928** [comment]
@thomcrowe great!  I would suggest we change "Contributor" to "Contributors" or "Collaborators" to ensure it is clear language.  I love this idea!

**Comment by thomcrowe** [comment]
Sounds great. @felixwidjaja can you update to “Contributors”?

**Comment by felixwidjaja** [comment]
@thomcrowe Okay on progress.

**Comment by ronggur** [comment]
PR ready https://github.com/tinkerbell/tinkerbell.org/pull/85

**Comment by felixwidjaja** [comment]
@mmlb @gauravgahlot I suggest we go with manual first, then improve with auto fetch the contributors. Cool?
We will need this auto fetch script in the future with the new theme & CMS coming.

**Comment by mrmrcoleman** [comment]
I'm ok with manual for now so long as we have a human process to review and create updates periodically. Monthly is likely sufficient. @thomcrowe Can you take care of this please?

**Comment by thomcrowe** [comment]
You bet. Let's go manual for now and I will be send in updates as an issue at the beginning of every month until we can automate that process.

Thanks.
