### ISSUE TITLE
Tinkerbell.org Hugo doesn't build locally

### ISSUE THREAD

**Issue by thomcrowe** [tinkerbell/tinkerbell.org#90]
We have not been able to build the Tinkerbell Hugo site locally. We need to be able to build locally to test and iterate, especially on docs. There are errors are listed below:

Building sites … WARN 2020/06/29 15:03:12 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
ERROR 2020/06/29 15:03:12 render of "page" failed: execute of template failed: template: _default/single.html:1:3: executing "_default/single.html" at <partial "header.html" .>: error calling partial: execute of template failed: template: partials/header.html:28:7: executing "partials/header.html" at <partial "menu.html" .>: error calling partial: "/Users/thomcrowe/documents/packet/tinkerbell.org/layouts/partials/menu.html:99:23": execute of template failed: template: partials/menu.html:99:23: executing "section-tree-nav" at <(not .Params.hidden) or $.showhidden>: can't give argument to non-function not .Params.hidden
ERROR 2020/06/29 15:03:12 render of "page" failed: execute of template failed: template: _default/single.html:1:3: executing "_default/single.html" at <partial "header.html" .>: error calling partial: execute of template failed: template: partials/header.html:28:7: executing "partials/header.html" at <partial "menu.html" .>: error calling partial: "/Users/thomcrowe/documents/packet/tinkerbell.org/layouts/partials/menu.html:99:23": execute of template failed: template: partials/menu.html:99:23: executing "section-tree-nav" at <(not .Params.hidden) or $.showhidden>: can't give argument to non-function not .Params.hidden
ERROR 2020/06/29 15:03:12 render of "page" failed: execute of template failed: template: _default/single.html:1:3: executing "_default/single.html" at <partial "header.html" .>: error calling partial: execute of template failed: template: partials/header.html:28:7: executing "partials/header.html" at <partial "menu.html" .>: error calling partial: "/Users/thomcrowe/documents/packet/tinkerbell.org/layouts/partials/menu.html:99:23": execute of template failed: template: partials/menu.html:99:23: executing "section-tree-nav" at <(not .Params.hidden) or $.showhidden>: can't give argument to non-function not .Params.hidden
ERROR 2020/06/29 15:03:12 render of "page" failed: execute of template failed: template: _default/single.html:1:3: executing "_default/single.html" at <partial "header.html" .>: error calling partial: execute of template failed: template: partials/header.html:28:7: executing "partials/header.html" at <partial "menu.html" .>: error calling partial: "/Users/thomcrowe/documents/packet/tinkerbell.org/layouts/partials/menu.html:99:23": execute of template failed: template: partials/menu.html:99:23: executing "section-tree-nav" at <(not .Params.hidden) or $.showhidden>: can't give argument to non-function not .Params.hidden
Built in 71 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:1:3: executing "_default/single.html" at <partial "header.html" .>: error calling partial: execute of template failed: template: partials/header.html:28:7: executing "partials/header.html" at <partial "menu.html" .>: error calling partial: "/Users/thomcrowe/documents/packet/tinkerbell.org/layouts/partials/menu.html:99:23": execute of template failed: template: partials/menu.html:99:23: executing "section-tree-nav" at <(not .Params.hidden) or $.showhidden>: can't give argument to non-function not .Params.hidden

**Comment by thomcrowe** [comment]
@ronggur Do you have any insight on what needs to be done to make this work locally?

**Comment by gianarb** [comment]
I made a few tests and it builds locally but you need a particular version of hugo:

```
Hugo Static Site Generator v0.69.0/extended darwin/amd64 BuildDate: unknown
```

We have to figure out why it does not work with the newest version of hugo. But in the meantime you can use `nix-shell` and everything will work again
