### ISSUE TITLE
Prettier and/or Hugo not registering line breaks

### ISSUE THREAD

**Issue by thomcrowe** [tinkerbell/tinkerbell.org#96]
There seems to be a line break conflict somewhere between running prettier and deploying to staging/live environment where a line break in markdown isn't registered as a line break in live. It looks like prettier is removing the extra white space and taking away the break. Hugo appears to need that double spaces and a carriage return to display the break. 

Below are two screenshots, one showing the code for the new docs landing page and the landing page in staging. The contributor line, for example, is mashed into one paragraph instead of displaying the line break. 

![image](https://user-images.githubusercontent.com/7960458/86635289-84131a00-bf98-11ea-837d-bf66384798b0.png)

![image](https://user-images.githubusercontent.com/7960458/86635363-9a20da80-bf98-11ea-9053-887dd21cac22.png)

**Comment by thomcrowe** [comment]
Is there a better way we can ensure the line breaks are preserved after running prettier when hugo builds @ronggur?

**Comment by ronggur** [comment]
@thomcrowe  according to this issue, it is not possible https://github.com/prettier/prettier/issues/4131#issuecomment-404603823

But we can ignore it with this documentation https://prettier.io/docs/en/ignore.html

**Comment by jacobweinstock** [comment]
prettier is not used at the moment and the refactor does not seem to have this issue.
